_config.yml  



remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Vikash Giri]
description: [MCA student passionate about Web Development, Machine Learning, AI, and problem-solving. I build practical projects and continuously explore new technologies.
]
